name: Maven Dependency Updates

on:
  schedule:
    - cron: "00 11 * * 1"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    uses: dfuchss/actions/.github/workflows/maven-update.yml@main
    with:
      auto-digit: "Patch"
    secrets:
      PAT: ${{ secrets.PAT }}
